export const GRADE_CHANGE_START = "GRADE_CHANGE_START";
export const GRADE_CHANGE_SUCCESS = "GRADE_CHANGE_SUCCESS";
export const GRADE_CHANGE_FAIL = "GRADE_CHANGE_FAIL";

export const GET_ASSESSMENT_START = "GET_ASSESSMENT_START";
export const GET_ASSESSMENT_SUCCESS = "GET_ASSESSMENT_SUCCESS";
export const GET_ASSESSMENT_FAIL = "GET_ASSESSMENT_FAIL";