export const SINGLE_STUDENT_INFO_PENDING = "SINGLE_STUDENT_INFO_PENDING"
export const SINGLE_STUDENT_INFO_SUCCESS = "SINGLE_STUDENT_INFO_SUCCESS"
export const SINGLE_STUDENT_INFO_FAILED = "SINGLE_STUDENT_INFO_FAILED"
