export const CREATE_REPORT_CARD_START = "CREATE_REPORT_CARD_START";
export const CREATE_REPORT_CARD_SUCCESS = "CREATE_REPORT_CARD_SUCCESS";
export const CREATE_REPORT_CARD_FAILED = "CREATE_REPORT_CARD_FAILED";
export const GET_REPORT_CARD_START = "GET_REPORT_CARD_START";
export const GET_REPORT_CARD_SUCCESS = "GET_REPORT_CARD_SUCCESS";
export const GET_REPORT_CARD_FAILED = "GET_REPORT_CARD_FAILED";
