export const ASSIGN_CLASS_PENDING = "ASSIGN_CLASS_PENDING";
export const ASSIGN_CLASS_SUCCESS = "ASSIGN_CLASS_SUCCESS";
export const ASSIGN_CLASS_FAILED = "ASSIGN_CLASS_FAILED";

export const CREATE_CLASS_PENDING = "CREATE_CLASS_PENDING";
export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
export const CREATE_CLASS_FAILED = "CREATE_CLASS_FAILED";
export const CREATE_CLASS_CLEAR_SUCCESS = "CREATE_CLASS_CLEAR_SUCCESS";

export const GET_TEACHERS_PENDING = "GET_TEACHERS_PENDING";
export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS";
export const GET_TEACHERS_FAILED = "GET_TEACHERS_FAILED";

export const ASSIGN_TEACHERS_PENDING = "GET_TEACHERS_PENDING";
export const ASSIGN_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS";
export const ASSIGN_TEACHERS_FAILED = "GET_TEACHERS_FAILED";

export const ASSIGN_STUDENT_PENDING = "GET_STUDENT_PENDING";
export const ASSIGN_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const ASSIGN_STUDENT_FAILED = "GET_STUDENT_FAILED";

export const CHANGE_HOME_ROOM_PENDING = "CHANGE_HOME_ROOM_PENDING";
export const CHANGE_HOME_ROOM_SUCCESS = "CHANGE_HOME_ROOM_SUCCESS";
export const CHANGE_HOME_ROOM_FAILED = "CHANGE_HOME_ROOM_FAILED";
