export const STUDENT_ASSESMENT_PENDING = "STUDENT_ASSESMENT_PENDING";
export const STUDENT_ASSESMENT_SUCCESS = "STUDENT_ASSESMENT_SUCCESS";
export const STUDENT_ASSESMENT_FAILED = "STUDENT_ASSESMENT_FAILED";
