export const NOTIFICATION_START = "NOTIFICATION_START";
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_FAILED = "NOTIFICATION_FAILED";

export const MY_NOTIFICATION_START = "MY_NOTIFICATION_START";
export const MY_NOTIFICATION_SUCCESS = "MY_NOTIFICATION_SUCCESS";
export const MY_NOTIFICATION_FAILED = "MY_NOTIFICATION_FAILED";

export const ADD_NOTIFICATION_START = "ADD_NOTIFICATION_START";
export const ADD_NOTIFICATION_SUCCESS = "ADD_NOTIFICATION_SUCCESS";
export const ADD_NOTIFICATION_FAILED = "ADD_NOTIFICATION_FAILED";
