export const CREATE_TEACHER_PENDING = "CREATE_TEACHER_PENDING";
export const CREATE_TEACHER_SUCCESS = "CREATE_TEACHER_SUCCESS";
export const CREATE_TEACHER_FAILED = "CREATE_TEACHER_FAILED";

export const UPDATE_TEACHER_PENDING = "UPDATE_TEACHER_PENDING";
export const UPDATE_TEACHER_SUCCESS = "UPDATE_TEACHER_SUCCESS";
export const UPDATE_TEACHER_FAILED = "UPDATE_TEACHER_FAILED";
