export const ADMIN_ATTENDANCE_START = "ADMIN_ATTENDANCE_PENDING";
export const ADMIN_ATTENDANCE_SUCCESS = "ADMIN_ATTENDANCE_SUCCESS";
export const ADMIN_ATTENDANCE_FAILED = "ADMIN_ATTENDANCE_FAILED";

export const ATTEND_GOT_DATA_START = "ATTEND_GOT_DATA_PENDING";
export const ATTEND_GOT_DATA_SUCCESS = "ATTEND_GOT_DATA_SUCCESS";
export const ATTEND_GOT_DATA_FAILED = "ATTEND_GOT_DATA_FAILED";
