export const GET_CLASS_LIST_PENDING = "GET_CLASS_LIST_PENDING";
export const GET_CLASS_LIST_SUCCESS = "GET_CLASS_LIST_SUCCESS";
export const GET_CLASS_LIST_FAILED = "GET_CLASS_LIST_FAILED";
export const SET_FILTER = "SER_FILTER";
export const GET_A_CLASS_SUCCESS = "GET_A_CLASS_SUCCESS";
export const GET_A_CLASS_PENDING = "GET_A_CLASS_PENDING";
export const GET_A_CLASS_FAILED = "GET_A_CLASS_FAILED";
