export const GET_CLASS_LIST_PENDING = "GET_CLASS_LIST_PENDING";
export const GET_CLASS_LIST_SUCCESS = "GET_CLASS_LIST_SUCCESS";
export const GET_CLASS_LIST_FAILED = "GET_CLASS_LIST_FAILED";
export const SET_FILTER = "SER_FILTER"
