export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS";
export const ALL_USER_FAILED = "ALL_USER_FAILED";
export const ALL_USER_PENDING = "ALL_USER_PENDING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
