export const CREATE_ATTENDANCE_START = "CREATE_ATTENDANCE_PENDING";
export const CREATE_ATTENDANCE_SUCCESS = "CREATE_ATTENDANCE_SUCCESS";
export const CREATE_ATTENDANCE_FAILED = "CREATE_ATTENDANCE_FAILED";
