export const GET_STUDENT_ATTENDANCES_START = "GET_STUDENT_ATTENDANCES_START";
export const GET_STUDENT_ATTENDANCES_SUCCESS =
  "GET_STUDENT_ATTENDANCES_SUCCESS";
export const GET_STUDENT_ATTENDANCES_FAILED = "GET_STUDENT_ATTENDANCES_FAILED";
