export const CREATE_ASSESSMENT_START = "CREATE_ASSESSMENT_PENDING";
export const CREATE_ASSESSMENT_SUCCESS = "CREATE_ASSESSMENT_SUCCESS";
export const CREATE_ASSESSMENT_FAILED = "CREATE_ASSESSMENT_FAILED";
