export const REQUEST_STUDENTS_PENDING = "REQUEST_STUDENTS_PENDING";
export const REQUEST_STUDENTS_SUCCESS = "REQUEST_STUDENTS_SUCCESS";
export const REQUEST_STUDENTS_FAILED = "REQUEST_STUDENTS_FAILED";
export const GET_ALL_STUDENTS_PENDING = "GET_ALL_STUDENTS_PENDING";
export const GET_ALL_STUDENTS_SUCCESS = "GET_ALL_STUDENTS_SUCCESS";
export const GET_ALL_STUDENTS_FAILED = "GET_ALL_STUDENTS_FAILED";
export const REQUEST_STUDENTS_BY_FILTER_PENDING =
  "REQUEST_STUDENTS_BY_FILTER_PENDING";
export const REQUEST_STUDENTS_BY_FILTER_SUCCESS =
  "REQUEST_STUDENTS_BY_FILTER_SUCCESS";
export const REQUEST_STUDENTS_BY_FILTER_FAILED =
  "REQUEST_STUDENTS_BY_FILTER_FAILED";
export const REQUEST_STUDENTS_BY_FILTER_SELECTED =
  "REQUEST_STUDENTS_BY_FILTER_SELECTED";

  